branches:
  only:
  - master
before_script:
- docker login -u $dockerhubuser -p $dockerhubpassword docker.io
script:
- make build
- make publish
- make deploy
before_install:
- openssl aes-256-cbc -K $encrypted_4394e5b6e01b_key -iv $encrypted_4394e5b6e01b_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 700 id_rsa
