branches:
  only:
  - master
before_script:
- docker login -u $dockerhubuser -p $dockerhubpassword docker.io
script:
- make build
- make publish
- make deploy
before_install:
- openssl aes-256-cbc -K $encrypted_4394e5b6e01b_key -iv $encrypted_4394e5b6e01b_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 700 id_rsa
notifications:
  slack:
    rooms:
      secure: NZfD6mU1IzDV3skcSCg6SxNBIG8hdPwhi0kmdKnwdMa7yBbK01v4GwFUlsKMsQPRB+kTviFiYzmZuxAbBgPs96upStY4wTC4bd2m7oCU4CrkbTOdzuORc1CxFgdHsiwUSE1emyOqUQKRSdEJsfzL1hkCBFnLQaY1squQmtKb9O8phNAsLzdH/q20aiRFtI06XLV+7sI+zJsSY7RjrKQLTqfsOoVWrrqb+BAHpBkm/0XKxegQ/Lgq+IFlKYLjHbdXH6PpaYSDyrQz4fcVZQhSt+Gae9QB+OF0D2VuAeqfM5oWFB56M6FvTmRzPXod7v5LZPgOtlH5nqDhNZBxKNOUu5yGS5BSXjW/9VI2YzXo51cVXtuvMSj0SSrw9ZkQdTvU9m+EMKZPIOnfg5wAn/Un8u50IKiu16G9z/yF813QC37A/XaiC5nSTKDOzOjUzsVS54hKwo1t6UGon43fptIulE5Od9S+j+ufn+7Uj0P0CjYc2O1u5FTjBwLXqDHC060J+25asydZtw6mSnAw+0GyWdqC+yqynG+2PfbAtRQsvzoha6wwXNKIr/lWOrfCFmlLwMqcD7VZ4aYkEfD45sQfcdl22DjFAwnKlWq/nFyiDpPQYSW8ooBX+4MAm/zV8NhrA9VmmD4G822vye5916h1DEGYBjIDrNx1HyBGzxn1yqY=
env:
  global:
    secure: ENGGcVQwwEObex+v3yba5DPoiVQPgSmz612gciORpckN3WpEGyw9gc7SI27IcT2udVGgqg4+GtHCpRYj3f3WeYcqkXqi9W3lbiOLZll+g7O1KJDW8Ac1mc9vqC59wbKHyRdIoYOz9qard592gWYgYapMGxIW71vZ9Eo2p9bXN0LoilWrqNxywwwrq3TWabFeBJtrkpQpFby83YWM+ZnnQWDW0RccgRhVVO4kzz+8Yj+w/BHLj2yoKQChTP+2d0PZxgUDbRjxNzA7BF7MDf92XBKdkw2rzd/TGdZW4HQuGRKCAU3mt+JWjh740YeLWZvjAJu9NXSb4T20imy3GxGATDMYjjpVpJGsC4RWb9jBN/mjCP/BovF8Wr8Kz5WDjHKmOyN9DYhumKPzXd7W+Ohk5uDie3PzzcBaXVLQvbSfVXcrowJeli6Vm0rQQm4CIAVfrs3iuI7xEbT7kVR4iI0PDyd2VIs1vTSoZby4AIe/p26K83VF+761nesvBwfiuBLVNzWhRuAqOKvwd+T92C0RbOKgCrrfhKYNQxj1njlhZpyssvYU5xco+DWJmjzpbbaY1RPFOq6ouGzfcYMo4nnEVhxCY9ltrxK/RCYX2VGaz+FecJJgj0c21i1LVg1umkaSJ5bwMSBIWxRK4Wke2D+ypHkBWpteMjHSmppqibxBCyI=
